apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gke-autoneg-controller.fullname" . }}-controller-manager
  labels:
    app: autoneg
    control-plane: controller-manager
  {{- include "gke-autoneg-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      app: autoneg
      control-plane: controller-manager
    {{- include "gke-autoneg-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: autoneg
        control-plane: controller-manager
      {{- include "gke-autoneg-controller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        name: manager
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "gke-autoneg-controller.fullname" . }}-autoneg
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gke-autoneg-controller.fullname" . }}-autoneg
  labels:
  {{- include "gke-autoneg-controller.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}