apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gke-autoneg-controller.fullname" . }}-manager-rolebinding
  labels:
    app: autoneg
  {{- include "gke-autoneg-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gke-autoneg-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "gke-autoneg-controller.fullname" . }}-autoneg'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gke-autoneg-controller.fullname" . }}-manager-role
  labels:
    app: autoneg
  {{- include "gke-autoneg-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update