---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoneg
  namespace: autoneg-system
  annotations:
    iam.gke.io/gcp-service-account: tk-lcl-config-connector@tk-v3-lcl-3006.iam.gserviceaccount.com 	