---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: sample-apps
  labels:
    project: sample-apps
    app: hello-world
    cost-center: cc-001
spec: 
  selector: 
    app: hello-world
  ports: 
  - name: http
    port: 8080
    protocol: TCP