---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  users.session.duration: 24h
  passwordPattern: ^.{8,32}$
  kustomize.enabled: true
  jsonnet.enabled: true
  helm.enabled: true
  kustomize.buildOptions: --load_restrictor none
  kustomize.path.v3.9.1: /custom-tools/kustomize_3_9
  kustomize.buildOptions.v3.9.1: --enable_kyaml true
  kustomize.version.v3.5.1: /custom-tools/kustomize_3_5_1
  kustomize.version.v3.5.4: /custom-tools/kustomize_3_5_4
  helm.valuesFileSchemes: http, https
  admin.enabled: "true"
  accounts.viewer: login
  accounts.viewer.enabled: "true"
  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "true"
  server.rbac.log.enforce.enable: "false"
  exec.enabled: "false"
  exec.shells: bash,sh,powershell,cmd
  oidc.tls.insecure.skip.verify: "false"
