apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "istio.fullname" . }}-d-default-validator
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "istio.fullname" . }}-
  labels:
  {{- include "istio.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: '{{ include "istio.fullname" . }}-d'
      namespace: '{{ .Release.Namespace }}'
      path: /validate
  failurePolicy: Ignore
  name: validation.istio.io
  rules:
  - apiGroups:
    - security.istio.io
    - networking.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  sideEffects: None