apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "istio.fullname" . }}-d-gateway-controller-istio-system
  labels:
    app: istiod
    release: istio
  {{- include "istio.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio.fullname" . }}-d-gateway-controller-istio-system
  labels:
    app: istiod
    release: istio
  {{- include "istio.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "istio.fullname" . }}-d-gateway-controller-istio-system'
subjects:
- kind: ServiceAccount
  name: '{{ include "istio.fullname" . }}-d'
  namespace: '{{ .Release.Namespace }}'