apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "istio.fullname" . }}-ingressgateway
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "istio.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "istio.fullname" . }}-ingressgateway
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "istio.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio.fullname" . }}-ingressgateway
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "istio.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    controller.autoneg.dev/neg:  "{'backend_services':{'80':[{'name':'"{{ .Values.ingressgateway.negConfig.backendName }}"','max_rate_per_endpoint':1000}]}}"
    networking.gke.io/load-balancer-type: Internal
spec:
  type: {{ .Values.ingressgateway.type }}
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  {{- include "istio.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ingressgateway.ports | toYaml | nindent 2 -}}