---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          workload: true
  template:
    metadata:
      name: '{{cluster}}-{{region}}-hello-world'
    spec:
      project: sample-apps
      source:
        repoURL: https://github.com/timbohiatt/kubernetes-tools.git
        targetRevision: HEAD
        path: sample-apps/argocd-apps/hello-world/manifests
      destination:
        server: '{{server}}'
        namespace: hello-world
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

          