---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          workload: "true"
  template:
    metadata:
      name: '{{name}}-hello-world'
    spec:
      project: sample-apps
      source:
        path: sample-apps/argocd-apps/hello-world/manifests
        repoURL: 'https://github.com/timbohiatt/kubernetes-tools'
        targetRevision: HEAD
      destination:
        server: '{{server}}'
        namespace: hello-world
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        #syncOptions:
        #  - CreateNamespace=true

          