---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-ui-tjhiatt
  namespace: argocd
spec:
  host: argocd.tjhiatt.dev
  prefix: /
  service: argocd-server:443
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-cli-tjhiatt
  namespace: argocd
spec:
  # NOTE: the port must be ignored if you have strip_matching_host_port enabled on envoy
  host: argocd.tjhiatt.dev:443
  prefix: /
  service: argocd-server:80
  regex_headers:
    Content-Type: "^application/grpc.*$"
  grpc: true
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-ui-timhiatt
  namespace: argocd
spec:
  host: argocd.timhiatt.dev
  prefix: /
  service: argocd-server:443
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-cli-timhiatt
  namespace: argocd
spec:
  # NOTE: the port must be ignored if you have strip_matching_host_port enabled on envoy
  host: argocd.timhiatt.dev:443
  prefix: /
  service: argocd-server:80
  regex_headers:
    Content-Type: "^application/grpc.*$"
  grpc: true
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
  - "argocd.tjhiatt.dev" # Change it to "*" if you dont have a host name yet
  - "argocd.timhiatt.dev" # Change it to "*" if you dont have a host name yet
  gateways:
  - istio-system/ingress-gateway
  http:
  - route:
    - destination:
        host: "argocd.tjhiatt.dev" # Change it to "*" if you dont have a host name yet
        port:
          number: 80
    - destination:
        host: "argocd.timhiatt.dev" # Change it to "*" if you dont have a host name yet
        port:
          number: 80