---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: sample-apps
  annotations:
  #  networking.gke.io/load-balancer-type: "Internal"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer 
  selector: 
    app: hello-world
  ports:
    -
      name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    -
      name: https
      port: 443
      protocol: TCP
      targetPort: 8443